version: '3.9'

services:
  app:
    container_name: koushikpuppala
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  node_modules:
    name: koushikpuppala-node_modules
