export type { AboutSchemaProps } from './about'
export type { EducationSchemaProps } from './education'
export type { ExperienceSchemaProps } from './experience'
export type { HomeSchemaProps } from './home'
export type { ProjectSchemaProps } from './projects'
export type { ServicesSchemaProps } from './services'
