name: Preview Build and Deployment

env:
  NODE_ENV: preview
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore: master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack before setting Node
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install
      - name: Install Vercel Globally
        run: npm install --global vercel@latest
      - name: Pull the environment variables
        run: vercel pull --yes ./ --environment=${{ env.NODE_ENV }} --git-branch=${{ github.ref_name }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Upload Project Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: none
    environment:
      name: Preview
      url: ${{ steps.deployment_url.outputs.deployment_url }}
    steps:
      - name: Download Project Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
      - name: Assign Deployment URL
        run: vercel alias --token=${{ secrets.VERCEL_TOKEN }} set `cat domain.txt` ${{ env.NODE_ENV }}.koushikpuppala.com
      - name: Save Deployment ID
        run: echo ::set-output name=deployment_id::`cat .vercel/project.json | jq -r '.id'`
        id: deployment_id
      - name: Save Deployment URL
        run: echo ::set-output name=deployment_url::https://${{ env.NODE_ENV }}.koushikpuppala.com
        id: deployment_url
      - name: Cleanup
        run: rm domain.txt
      - name: Set Deployment URL
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            core.setOutput('deployment_url', '${{ steps.deployment_url.outputs.deployment_url }}')
            core.setOutput('deployment_id', '${{ steps.deployment_id.outputs.deployment_id }}')
