name: Preview Build and Deployment

env:
  NODE_ENV: preview
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore: master

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: commit-check/commit-check-action@v1
        with:
          message: false
          branch: false
          author-name: true
          author-email: true
          commit-signoff: true
          dry-run: true
          job-summary: true
  build-deploy:
    runs-on: ubuntu-latest
    needs: [commit-check]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack before setting Node
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install
      - name: Install Vercel Globally
        run: npm install --global vercel@latest
      - name: Pull the environment variables
        run: vercel pull --yes ./ --environment=${{ env.NODE_ENV }} --git-branch=${{ github.ref_name }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
