name: Production Build and Deployment

env:
  NODE_ENV: production
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack before setting Node
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install
      - name: Install Vercel Globally
        run: npm install --global vercel@latest
      - name: Pull the environment variables
        run: vercel pull --yes ./ --environment=${{ env.NODE_ENV }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Upload Project Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: none
    steps:
      - name: Download Project Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - name: Save Deployment ID
        id: deployment_id
        run: echo "deployment_id=`cat .vercel/project.json | jq -r '.id'`" >> $GITHUB_OUTPUT
      - name: Save Deployment URL
        id: deployment_url
        run: echo "deployment_url=https://koushikpuppala.com" >> $GITHUB_OUTPUT
    outputs:
      deployment_id: ${{ steps.deployment_id.outputs.deployment_id }}
      deployment_url: ${{ steps.deployment_url.outputs.deployment_url }}

  release:
    runs-on: ubuntu-latest
    needs: [deploy]
    permissions:
      contents: none
    environment:
      name: Production
      url: ${{ needs.deploy.outputs.deployment_url }}
    steps:
      - name: Script for Deployment URL and ID
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            core.setOutput('deployment_url', '${{ needs.deploy.outputs.deployment_url }}')
            core.setOutput('deployment_id', '${{ needs.deploy.outputs.deployment_id }}')
