name: Production Build and Deployment

env:
  NODE_ENV: production
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack before setting Node
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install
      - name: Check for Code Formatting
        run: yarn check:format
      - name: Check Types for TypeScript
        run: yarn check:types
  build-deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack before setting Node
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Vercel Globally
        run: npm install --global vercel@latest
      - name: Install dependencies
        run: yarn install
      - name: Pull the environment variables
        run: vercel pull --yes --environment=${{ env.NODE_ENV }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuild --prod --token=${{ secrets.VERCEL_TOKEN }}
